default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: check-toml
        stages: [commit]


  # HTML, CSS, TypeScript, Markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        name: prettier (Markdown)
        types: [file]
        files: \.md$
      - id: prettier
        name: prettier (HTML & CSS)
        types: [file]
        files: \.(html|css)$
      - id: prettier
        name: prettier (TypeScript)
        types: [file]
        files: \.(ts|tsx)$

  # python
  - repo: https://github.com/ambv/black
    rev: 23.3.0  # make sure to match what goes in requirements/dev.txt
    hooks:
      - id: black
        args: [--diff, --check]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--config-file, api/pyproject.toml, --pretty]
