default_stages: [commit]

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: check-toml
        stages: [commit]


  # HTML, CSS, TypeScript, Markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        name: prettier (Markdown)
        types: [file]
        files: \.md$
      - id: prettier
        name: prettier (HTML & CSS)
        types: [file]
        files: \.(html|css)$
      - id: prettier
        name: prettier (TypeScript)
        types: [file]
        files: \.(ts|tsx)$

  # python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.276
    hooks:
      - id: ruff
        name: 'api: ruff'
        files: '^api/(src|tests)/.*\.py'
        args: [--fix, --config=api/pyproject.toml]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # make sure to match what goes in requirements/dev.txt
    hooks:
      - id: isort
        name: 'api: isort'
        files: '^api/(src|tests)/.*\.py'
        args: [--settings-path=api/pyproject.toml]

  - repo: https://github.com/ambv/black
    rev: 23.3.0  # make sure to match what goes in requirements/dev.txt
    hooks:
      - id: black
        name: 'api: black'
        files: '^api/(src|tests)/.*\.py'
        args: [--config=api/pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        name: 'api: mypy'
        files: '^api/(src|tests)/.*\.py'
        args: [--config-file=api/pyproject.toml, --pretty, api]
        pass_filenames: false  # do not pass files as arguments to the script
