version: "3.8"

services:
  oye-api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    image: oye-api-dev
    container_name: oye-api-dev
    command: python -m src.adapters.api
    ports:
      - "5000:5000"
    environment:
      - DEBUG=true
      - DB_PATH=${DB_PATH}
      - "NATS_URL=${NATS_URL:-nats://nats:4222}"
    volumes:
      - ./api:/app
    depends_on:
      - nats
    # healthcheck:

  oye-api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: release
    image: oye-api
    container_name: oye-api
    command: python -m src.adapters.api
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - DB_PATH=${DB_PATH}
    volumes:
      - ./api:/app
    # healthcheck:

  nats:
    image: 'nats:2.9.19'
    # entrypoint
    # expose:  # not visible to host, only to other containers
    #   - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    hostname: nats-server
    # src: https://nats.io/blog/docker-compose-plus-nats/

  oye-event-handler-dev:
    build:
      context: ./event_handler
      dockerfile: Dockerfile
      target: dev
    image: oye-event-handler-dev
    container_name: oye-event-handler-dev
    command: python -m src.adapters.event_handler
    environment:
      - "NATS_URL=${NATS_URL:-nats://nats:4222}"
    volumes:
      - ./event_handler:/app
    depends_on:
      - nats
