version: "3.8"

services:
  oye-api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    image: oye-api-dev
    container_name: oye-api-dev
    command: python -m src.adapters.api
    ports:
      - "5000:5000"
    environment:
      - DEBUG=true
      - DB_PATH=${DB_PATH:-oye-api-local.sqlite}
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - PYTHONBREAKPOINT=${PYTHONBREAKPOINT}
    volumes:
      - ./api:/app
    # healthcheck:

  oye-api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: release
    image: oye-api
    container_name: oye-api
    command: python -m src.adapters.api
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - DB_PATH=${DB_PATH:-oye-api.sqlite}
    volumes:
      - ./api:/app
    # healthcheck:

  # oye-event-handler-dev:
  #   build:
  #     context: ./event_handler
  #     dockerfile: Dockerfile
  #     target: dev
  #   image: oye-event-handler-dev
  #   container_name: oye-event-handler-dev
  #   command: python -m src.adapters.event_handler
  #   volumes:
  #     - ./event_handler:/app

  db:
    image: 'postgres:16.1-alpine3.19'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-default_database} # automatically created at first launch
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
